TechCollector/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('techcollector.urls')),
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls'))
]

techcollector/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('tech/<int:tech_id>',views.techdetail, name='techdetail'),
    path('tech/create',views.TechCreate.as_view(),name='tech_create'),
    path('tech/perk/create',views.PerkCreate.as_view(),name='perk_create'),
    path('tech/<int:pk>/update',views.TechUpdate.as_view(),name='tech_update'),
    path('tech/<int:pk>/delete',views.TechDelete.as_view(),name='tech_delete'),
   
    path('tech/<int:tech_id>/add_provider',views.add_provider, 
    name='add_provider'),
    path('tech/<int:tech_id>/provider/<int:provider_id>,',views.delete_provider,name="delete_provider"),
    path('tech/<int:tech_id>/assoc_perk/<int:perk_id>',views.assoc_perk,name='assoc_perk'),

    path('accounts/signup',views.signup, name='signup')

]
   

techcollector/models.py
from audioop import reverse
from pyexpat import model
from django.db import models
from django.forms import CharField
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class Perks(models.Model):
    name=models.CharField(max_length=100)
    value=models.CharField(max_length=100)

    def __str__(self):
        return self.name 

    # def get_absolute_url(self):
    #     return reverse('perkdetail',kwargs={'tech_id':self.id})     


class Tech(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length =100)
    specs = models.TextField(max_length=255)
    price = models.IntegerField()
    perk = models.ManyToManyField(Perks)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('techdetail',kwargs={'tech_id':self.id})

    class Meta:
        ordering = ['id']    



class Providers(models.Model):
    name=models.CharField(max_length=100)
    price=models.IntegerField()
    stock=models.BooleanField()

    def __str__(self):
        return self.name
    tech= models.ForeignKey(Tech,on_delete=models.CASCADE)    

    class Meta:
        ordering = ['-id']


 

techcollector/forms.py
from django.forms import ModelForm
from .models import Providers

class  ProvidersForm(ModelForm):
    class Meta:
        model = Providers
        fields =['name','price','stock']

techcollector/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Tech,Providers,Perks
from django.views.generic import CreateView,DeleteView,UpdateView,ListView,DetailView
from .forms import ProvidersForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.
def home(request):
    techs = Tech.objects.all()
    return render(request,'home.html', {'techs':techs})

@login_required 
def techdetail(request,tech_id):
    tech = Tech.objects.get(id=tech_id)
    providers_form = ProvidersForm()

    perks_not_added = Perks.objects.exclude(id__in = tech.perk.all().values_list('id'))

    return render(request,'techdetail.html',{'tech':tech,'providers_form':providers_form, 'perks':perks_not_added})

@login_required    
def add_provider(request,tech_id):
    form = ProvidersForm(request.POST)
    if form.is_valid():
        new_provider = form.save(commit=False)
        new_provider.tech_id = tech_id 
        new_provider.save()
    return redirect('techdetail', tech_id=tech_id)                  

@login_required  
def delete_provider(request, tech_id, provider_id):
    provider = Providers.objects.get(id=provider_id)
    provider.delete()
    return redirect('techdetail',tech_id=tech_id)

@login_required  
def assoc_perk(request,tech_id,perk_id):
    Tech.objects.get(id=tech_id).perk.add(perk_id)
    return redirect('techdetail',tech_id=tech_id)


def signup(request):
    error_message= ''
    if request.method == 'POST':
        form=UserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - Try again'
    form=UserCreationForm()
    context = {'form':form, 'error_message':error_message}
    return render(request,'registration/signup.html',context)                


class TechCreate(LoginRequiredMixin,CreateView):
       model = Tech
       fields = ['name','type','specs','price']
       def form_valid(self,form):
           form.instance.user = self.request.user
           return super().form_valid(form)


class TechUpdate(LoginRequiredMixin,UpdateView):
    model= Tech
    fields = ['type','specs','price']       
       

class TechDelete(LoginRequiredMixin,DeleteView):
    model= Tech
    success_url = '/'

class PerkCreate(LoginRequiredMixin,CreateView):
    model = Perks
    fields = ['name','value']
    success_url = '/'    

techcollector/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    
    <title>TechCollector</title>
</head>
<body class="bg-slate-700 h-screen bckground">

    <nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
        <div class="container flex flex-wrap justify-between items-center mx-auto">
        <a href="/" class="flex items-center">
        <!-- <img src="/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo"> -->
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">TechCollector</span>
        </a>
        <div class="flex md:order-2">
        <button type="button" data-collapse-toggle="mobile-menu-3" aria-controls="mobile-menu-3" aria-expanded="false" class="md:hidden text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        </button>
        <div class="hidden relative md:block">
        <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        </div>
        <input type="text" id="search-navbar" class="block p-2 pl-10 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-sm focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
        </div>
        <button data-collapse-toggle="mobile-menu-3" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu-3" aria-expanded="false">
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
        </div>
        <div class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1" id="mobile-menu-3">
        <div class="relative mt-3 md:hidden">
        <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
        </div>
        <input type="text" id="search-navbar" class="block p-2 pl-10 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-sm focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
        </div>
        <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <li>
        <a href="{% url 'home' %}" class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
        </li>
        <li>
        <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">About</a>
        </li>
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'tech_create' %}" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Add Tech</a>
        </li>
        <li>
            <a href="{% url 'perk_create' %}" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Add Perk</a>
        </li>
        <li>
            <a href="{% url 'logout' %}" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Logout</a>
        </li>
        {% else %}
        <li>
            <a href="{% url 'login' %}" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Login</a>
        </li>
        <li>
            <a href="{% url 'signup' %}" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">signup</a>
        </li>
        {% endif %}
        </ul>
        </div>
        </div>
        </nav>
        
    {% block content %}
    {% endblock %}
</body>
</html>

techcollector/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="flex flex-wrap justify-center w-1/2 m-auto">
{% for tech in techs %}

{% if user.id == tech.user.id %}
<a href="{% url 'techdetail' tech.id %}" class="block p-6 m-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    {% else %}
    <a href="#" class="block p-6 m-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    {% endif %}

    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ tech.name }}</h5>
    <p class="font-normal text-gray-700 dark:text-gray-400">
        <span class="font-bold">{{ tech.type }}</p>
    <p class="font-normal text-gray-700 dark:text-gray-400"> <span class="font-bold">Specs :</span>  {{ tech.specs }}</p>
    <p class="font-normal text-gray-700 dark:text-gray-400"> <span class="font-bold">Price :</span>  ${{ tech.price }} +</p>
    </a>
    {% endfor %}
</div>
{% endblock %}
</body>
</html>

techcollector/templates/techcollector/perks_form.html
{% extends 'base.html' %}

{% block content %}
  
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <div class="w-fit mx-auto my-28 bg-slate-800">
   {% if object %}
    <h1 class="mx-16 text-sky-400 text-4xl p-5 ">Edit <span class=" text-sky-400 text-4xl  ">{{object.name}}</span></h1>
  {% else %}
    <h1 class="mx-16 text-sky-400 text-4xl p-5 ">Add perk</h1>
  {% endif %}
  <form action="" method="post" class="bg-slate-800 text-sky-400 shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table class="w-fit">
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-4 m-12 rounded focus:outline-none focus:shadow-outline">
  </form>
</div>
{% endblock %}

techcollector/templates/techcollector/tech_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div div class="block p-6 m-6 max-w-sm e rounded-lg border border-blue-200 shadow-md bg-gray-800 dark:border-gray-700 text-white mx-auto">
  <h1 class="font-bold text-gray-700 dark:text-gray-400">Delete Tech</h1>

  <h4 class="text-gray-700 dark:text-gray-400">Are you sure you want to delete <span class="font-bold">{{ tech.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-4 m-12 rounded focus:outline-none focus:shadow-outline">
    <a class="text-gray-700 dark:text-gray-400" href="{% url 'techdetail' tech.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

techcollector/templates/techcollector/tech_form.html
{% extends 'base.html' %}

{% block content %}
  
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <div class="w-fit mx-auto my-28 bg-slate-800">
   {% if object %}
    <h1 class="mx-16 text-sky-400 text-4xl p-5 ">Edit <span class=" text-sky-400 text-4xl  ">{{object.name}}</span></h1>
  {% else %}
    <h1 class="mx-16 text-sky-400 text-4xl p-5 ">Add Tech</h1>
  {% endif %}
  <form action="" method="post" class="bg-slate-800 text-sky-400 shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table class="w-fit">
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-4 m-12 rounded focus:outline-none focus:shadow-outline">
  </form>
</div>
{% endblock %}

techcollector/templates/techdetail.html
{% extends 'base.html' %}
{% block content %}

<div class="flex flex-col items-center">

<div class="block p-6 m-6 max-w-sm bg-white rounded-lg border border-blue-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{ tech.name }}</h5>
    <p class="font-normal text-gray-700 dark:text-gray-400"><span class="font-bold">{{tech.type}}</span> </p>
    <p class="font-normal text-gray-700 dark:text-gray-400">
        <span class="font-bold">Specs :</span>{{ tech.specs }}</p>
    <p class="font-normal text-gray-700 dark:text-gray-400">
        <span class="font-bold">Price :</span>  ${{ tech.price }}</p>
</div>
<div class="">
    <a  class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-4 m-12 rounded focus:outline-none focus:shadow-outline"href="{% url 'tech_update' tech.id %}">Edit</a>
    <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-4 m-12 rounded focus:outline-none focus:shadow-outline" href="{% url 'tech_delete' tech.id %}">Delete</a>
  </div>
  
  <div class="block p-6 m-6 max-w-sm bg-white rounded-lg border border-blue-200 shadow-md  dark:bg-gray-800 dark:border-gray-700 dark items-center">
    <table class="border-4 border-slate-500 text-white m-auto">
      <thead class="border-2 border-slate-500">
        <tr><th class="p-2 border-2 border-slate-500">Provider</th><th class="p-2 border-2 border-slate-500">Price</th><th class="p-2 border-2 border-slate-500">Availability</th></tr>
      </thead>
      <tbody>
        {% for provider in tech.providers_set.all %}
          <tr>
            <td class="p-2 text-center border-2 border-slate-500">{{provider.name}}</td>
            <td class="p-2 text-center border-2 border-slate-500">{{provider.price}}</td>
            <td class="p-2 text-center border-2 border-slate-500">{{provider.stock}}</td>
            <td class="border-2 border-slate-500"><form class="p-2" action="{% url 'delete_provider' tech.id provider.id %}" method="POST">
                {% csrf_token %}
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-2 rounded focus:outline-none focus:shadow-outline block m-auto">X</button>
            </form></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="my-14">
    <!-- new code below -->
    <h3 class="text-center text-white font-bold">Add a provider</h3>
    <form method="post" class="text-white text-center" action="{% url 'add_provider' tech.id %}">
      {% csrf_token %}
      {{ providers_form.as_table}}
      <input type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-2 rounded focus:outline-none focus:shadow-outline block m-auto" value="Add Provider">
    </form>
    </div>
  </div>

  <hr>
  <div class="flex ">
<div class="block p-6 m-6 max-w-sm bg-white rounded-lg border border-blue-200 shadow-md  dark:bg-gray-800 dark:border-gray-700 dark items-center text-white">
  <h1 class="text-center m-4 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Perks</h1>
  <div class="">
    {% if tech.perk.count %}
      
        <div class="card">
          <div class="card-content">
            <table class="border-4 border-slate-500 text-white">
              <tr class="border-2 ">
                <th class="p-2 text-center border-2 border-slate-500">Name</th>
                <th class="p-2 text-center border-2 border-slate-500">Value</th>
              </tr>
              {% for p in tech.perk.all %}
              <tr class="">
                <td class="p-2 text-center border-2 border-slate-500">{{ p.name }}</td>
                <td class="p-2 text-center border-2 border-slate-500">{{ p.value }}</td>
              </tr>
      {% endfor %}
            </table>
          </div>
        </div>
    {% else %}
      <h5>No Perks :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
</div>
  <div class="block p-6 m-6 max-w-sm bg-white rounded-lg border border-blue-200 shadow-md  dark:bg-gray-800 dark:border-gray-700 dark items-center text-white ">
    <h3 class="text-center m-4 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Available perks</h3>
    {% if perks.count %}
    <table class="border-4 border-slate-500 text-white">
     <tr class="border-2">
          <th class="p-2 text-center border-2 border-slate-500">Name</th>
          <th class="p-2 text-center border-2 border-slate-500">Value</th>
        </tr>
      {% for perk in perks.all %}
        <tr>
          <td class="p-2 text-center border-2 border-slate-500">{{ perk.name }}</td>
          <td class="p-2 text-center border-2 border-slate-500">{{ perk.value }}</td>
          <td class="border-2 border-slate-500 p-2">
            <form action="{% url 'assoc_perk' tech.id perk.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold p-2 rounded focus:outline-none focus:shadow-outline block m-auto">Add</button>
            </form>
          </td>
        </tr>
      
      {% endfor %}
    </table>
    {% else %}
      <h5>{{tech.name}} Already Has All perks </h5>
    {% endif %}
  </div>

</div>

</div>


</div>
{% endblock %}
</body>
</html>